/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface OpenbadgeDisplayer {
    /**
    * The openbadge image
    */
    'src': string;
  }
  interface OpenbadgeDisplayerAttributes extends StencilHTMLAttributes {
    /**
    * The openbadge image
    */
    'src'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'OpenbadgeDisplayer': Components.OpenbadgeDisplayer;
  }

  interface StencilIntrinsicElements {
    'openbadge-displayer': Components.OpenbadgeDisplayerAttributes;
  }


  interface HTMLOpenbadgeDisplayerElement extends Components.OpenbadgeDisplayer, HTMLStencilElement {}
  var HTMLOpenbadgeDisplayerElement: {
    prototype: HTMLOpenbadgeDisplayerElement;
    new (): HTMLOpenbadgeDisplayerElement;
  };

  interface HTMLElementTagNameMap {
    'openbadge-displayer': HTMLOpenbadgeDisplayerElement
  }

  interface ElementTagNameMap {
    'openbadge-displayer': HTMLOpenbadgeDisplayerElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
